# -*- coding: utf-8 -*-
"""Object Tracking Practical Impementation-Computer vision

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QWSOAY0aKK4Os5NdtbtMzys4JO-y35rN

# **PHASE 1:Video Acquisition**


---

Step 1.0 Download libraries
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
import os
import urllib.request
from IPython.display import display,HTML
import warnings
warnings.filterwarnings('ignore')

"""Step 1.1 Option A-Upload your own video

Click the upload button to select a video file from your computer
"""

# Step 1.1: Option A - Upload Your Own Video
from google.colab import files

print("Option A: Upload Your Own Video")
print("Click the button below to upload a video file.\n")

uploaded = files.upload()

if 'video_path' not in dir():
    video_path = None

if uploaded:
    video_path = list(uploaded.keys())[0]
    print(f"\nVideo uploaded successfully: '{video_path}'")
else:
    print("\nNo video uploaded. Proceeding to check for existing video.")

"""Step 1.2:Option B-Use Existing Video

Check if a video file already exists in the working directory.If found,use it.
"""

# Step 1.2: Option B - Check for Existing Video
print("\nOption B: Check for Existing Video")

# Show all files in current directory
print("\nFiles in current directory:")
print(os.listdir())

if 'video_path' not in dir():
    video_path = None

if video_path is None:
    video_extensions = ['.mp4', '.avi', '.mov', '.mkv', '.webm', '.flv']
    existing_videos = []

    for ext in video_extensions:
        for file in os.listdir('.'):
            if file.endswith(ext):
                existing_videos.append(file)

    if existing_videos:
        video_path = existing_videos[0]
        print(f"\nFound existing video: '{video_path}'")
        print(f"File size: {os.path.getsize(video_path) / (1024 * 1024):.2f} MB")
    else:
        print("\nNo existing video found.")

"""Step 1.3 Option C-Download sample video

If no video is uploaded or found,download a sample video of a moving object
"""

#step 1.3:Option C-Download sample Video
print("Option C:Download Sample Video")

if video_path is None:
  sample_url='https://github.com/opencv/opencv/raw/master/samples/data/vtest.avi'
  video_path='sample_video.avi'

  print("Downloading sample video")
  try:
    urllib.request.urlretrieve(sample_url,video_path)
    print(f"\n Sample video downloaded:'{video_path}'")
    print(f" File size: {os.path.getsize(video_path)/(10*24*1024):.2f MB}")
  except Exception as e:
    print(f"\n Error downloading sample video:{e}")
    print("Please upload your own video file")
    video_path=None

else:
  print(f"Video already uploaded:'{video_path}'")

"""Step 1.4:Validate and Display Video Information

Read video properties and display information to the user
"""

#Step 1.4: Validate and Display Video Information
print("\n Step 1.4:Video Information")

if video_path is None:
  print("ERROR:No Video available.Please upload a video.")
  exit()

# Open video capture
cap=cv2.VideoCapture(video_path)

if not cap.isOpened():
  print(f"Error opening video file:'{video_path}'")
  exit()

#Get video properties
fps=int(cap.get(cv2.CAP_PROP_FPS))
width=int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height=int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
total_frames=int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
duration=total_frames / fps if fps > 0 else 0

# Release capture for now
cap.release()

print("\n Video Loaded successfully")
print(f"  - Path: {video_path}")
print(f"  - Resolution: {width} x {height}")
print(f"  - FPS: {fps}")
print(f"  - Total frames: {total_frames}")
print(f"  - Duration: {duration:.2f} seconds")

# Check if video is valid
if total_frames==0:
  print("\nWARNING:Video has 0 frames.Please use a video file")
  exit()

"""Step 1.5 Display Video Preview

Show a preview of the video to the user
"""

# Step 1.5: Display Video Preview and Play Video
print("\nStep 1.5: Video Preview")

def display_video_preview(video_path, num_frames=5):
    """Display a few frames from the video."""
    cap = cv2.VideoCapture(video_path)

    fig, axes = plt.subplots(1, num_frames, figsize=(15, 4))
    fig.suptitle("Video Preview", fontsize=14)

    for i in range(num_frames):
        ret, frame = cap.read()
        if not ret:
            break

        # Convert BGR to RGB for display
        frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        axes[i].imshow(frame_rgb)
        axes[i].set_title(f"Frame {i+1}")
        axes[i].axis("off")

    cap.release()
    plt.tight_layout()
    plt.show()


def play_video(video_path, width=640, height=480):
    """Play the video in the notebook using an HTML5 video player."""
    from IPython.display import HTML, display
    from base64 import b64encode

    # Read video file and encode as base64
    with open(video_path, "rb") as f:
        video_data = f.read()

    video_base64 = b64encode(video_data).decode()

    # Create HTML5 video player
    video_html = f"""
    <video width="{width}" height="{height}" controls>
        <source src="data:video/mp4;base64,{video_base64}" type="video/mp4">
        Your browser does not support the video tag.
    </video>
    """

    display(HTML(video_html))


# Show sample frames
display_video_preview(video_path)

# Play the actual video
print("\nPlaying Video")
print("Use the controls below to play, pause, or adjust volume.")

if video_path.endswith(".avi"):
    print("Note: AVI format may not play in all browsers. Consider using MP4 format.")

try:
    play_video(video_path)
except Exception as e:
    print(f"Could not play video in notebook: {e}")
    print("Video file is still available for processing in the next phases.")

"""

---


# **Phase 2: Object Initialization**

Automatically detect and select the most prominent moving object in the first frame.




"""

# Phase 2: Object Initialization
print("\nPhase 2: Object Initialization")

from matplotlib.patches import Rectangle

# Read the first frame
cap = cv2.VideoCapture(video_path)
ret, first_frame = cap.read()
cap.release()

if not ret:
    print("Error: Could not read the first frame.")
    exit()

# Convert to grayscale
gray = cv2.cvtColor(first_frame, cv2.COLOR_BGR2GRAY)

# Apply Gaussian blur to reduce noise
blurred = cv2.GaussianBlur(gray, (5, 5), 0)

# Use edge detection to find object boundaries
edges = cv2.Canny(blurred, 50, 150)

# Find contours
contours, _ = cv2.findContours(edges, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

if not contours:
    print("No object detected. Using full frame.")
    h, w = first_frame.shape[:2]
    x, y, w, h = 0, 0, w, h
else:
    # Find the largest contour by area
    largest_contour = max(contours, key=cv2.contourArea)
    x, y, w, h = cv2.boundingRect(largest_contour)

    # Ensure minimum size
    min_size = 20
    if w < min_size or h < min_size:
        print(f"Detected object too small ({w}x{h}). Using full frame.")
        h, w = first_frame.shape[:2]
        x, y = 0, 0, w, h

bbox = (x, y, w, h)

# Store initial position
center_x = x + w // 2
center_y = y + h // 2
trajectory = [(center_x, center_y)]

print(f"Object detected: bbox=({x}, {y}, {w}, {h})")
print(f"Initial center: ({center_x}, {center_y})")

# Display the detected object
frame_rgb = cv2.cvtColor(first_frame, cv2.COLOR_BGR2RGB)
fig, ax = plt.subplots(1, 1, figsize=(8, 6))
ax.imshow(frame_rgb)
rect = Rectangle((x, y), w, h, linewidth=3, edgecolor='green', facecolor='none')
ax.add_patch(rect)
ax.plot(center_x, center_y, 'ro', markersize=8)
ax.set_title("Detected Object (Green Box) with Center (Red Dot)")
ax.axis("off")
plt.tight_layout()
plt.show()

"""---

# **Phase 3: Tracker Creation**

Initialize optical flow tracking using Lucas-Kanade method.
"""

# Phase 3: Tracker Creation (Optical Flow)
print("\nPhase 3: Tracker Creation")

# Parameters for optical flow
lk_params = dict(winSize=(15, 15),
                 maxLevel=2,
                 criteria=(cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT, 10, 0.03))

# Convert first frame to grayscale
old_gray = cv2.cvtColor(first_frame, cv2.COLOR_BGR2GRAY)

# Select points within the bounding box
x, y, w, h = bbox
mask = np.zeros_like(old_gray)
mask[y:y+h, x:x+w] = 255

# Find good features to track inside the bounding box
p0 = cv2.goodFeaturesToTrack(old_gray, mask=mask, maxCorners=50, qualityLevel=0.3, minDistance=7)

if p0 is None or len(p0) < 1:
    print("No features found. Using center point.")
    center_x = x + w // 2
    center_y = y + h // 2
    p0 = np.array([[[center_x, center_y]]], dtype=np.float32)

print(f"Tracking {len(p0)} feature points")

# Store tracking variables
tracker = {
    'old_gray': old_gray,
    'p0': p0,
    'lk_params': lk_params,
    'bbox': bbox,
    'center': (x + w // 2, y + h // 2)
}

print("Tracker initialized using optical flow")
print(f"Tracking object at bbox: {bbox}")

"""

---


# **Phase 4: Tracking Loop**

Process video frames, update tracker, and store trajectory points.

"""

# Phase 4: Tracking Loop (Colab Compatible)
print("\nPhase 4: Tracking Loop")

from google.colab.patches import cv2_imshow
import matplotlib.pyplot as plt

# Reopen video capture
cap = cv2.VideoCapture(video_path)

# Initialize trajectory with starting position
trajectory = [tracker['center']]

# Get initial data
old_gray = tracker['old_gray']
p0 = tracker['p0']
lk_params = tracker['lk_params']

frame_count = 0
display_interval = 30  # Display every 30th frame
display_frames = []    # Store frames for display

while True:
    ret, frame = cap.read()
    if not ret:
        break

    # Convert frame to grayscale
    frame_gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # Calculate optical flow
    p1, st, err = cv2.calcOpticalFlowPyrLK(old_gray, frame_gray, p0, None, **lk_params)

    # Select good points
    if p1 is not None:
        good_new = p1[st == 1]
        good_old = p0[st == 1]
    else:
        good_new = p0
        good_old = p0

    # Calculate new center
    if len(good_new) > 0:
        mean_x = int(np.mean(good_new[:, 0]))
        mean_y = int(np.mean(good_new[:, 1]))
        center = (mean_x, mean_y)
        trajectory.append(center)

        # Update bounding box
        dx = mean_x - tracker['center'][0]
        dy = mean_y - tracker['center'][1]
        x, y, w, h = bbox
        new_bbox = (x + dx, y + dy, w, h)
        bbox = new_bbox
        tracker['center'] = center

    # Store frame for display
    if frame_count % display_interval == 0:
        # Draw current state on frame
        x, y, w, h = [int(v) for v in bbox]
        cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 0), 2)
        cv2.circle(frame, center, 5, (0, 0, 255), -1)

        # Draw trajectory path
        for i in range(1, len(trajectory)):
            cv2.line(frame, trajectory[i-1], trajectory[i], (255, 0, 0), 2)

        cv2.putText(frame, f"Frame: {frame_count}", (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 255, 255), 2)
        display_frames.append(frame)

    frame_count += 1

    # Update previous frame and points
    old_gray = frame_gray.copy()
    p0 = good_new.reshape(-1, 1, 2) if len(good_new) > 0 else p0

# Release resources
cap.release()

print(f"Tracking complete! Processed {frame_count} frames.")
print(f"Trajectory points: {len(trajectory)}")

# Display the stored frames using matplotlib (no OpenCV GUI)
if display_frames:
    print(f"\nDisplaying {len(display_frames)} sample frames (every {display_interval} frames)")

    fig, axes = plt.subplots(2, 3, figsize=(15, 10))
    axes = axes.flatten()

    for i, ax in enumerate(axes):
        if i < len(display_frames):
            frame_rgb = cv2.cvtColor(display_frames[i], cv2.COLOR_BGR2RGB)
            ax.imshow(frame_rgb)
            ax.set_title(f"Frame {i * display_interval}")
            ax.axis("off")

    plt.tight_layout()
    plt.show()

"""

---
# **Phase 5: Visualization**
Plot the trajectory path and position over time.
"""

# Phase 5: Visualization
print("\nPhase 5: Visualization")

trajectory = np.array(trajectory)

# Create figure with two subplots
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

# Plot 1: 2D trajectory path
ax1.plot(trajectory[:, 0], trajectory[:, 1], 'b-', alpha=0.7)
ax1.plot(trajectory[0, 0], trajectory[0, 1], 'go', markersize=10, label='Start')
ax1.plot(trajectory[-1, 0], trajectory[-1, 1], 'ro', markersize=10, label='End')
ax1.scatter(trajectory[:, 0], trajectory[:, 1], c=range(len(trajectory)),
           cmap='viridis', s=8, alpha=0.5)
ax1.set_title('Object Trajectory Path')
ax1.set_xlabel('X Position (pixels)')
ax1.set_ylabel('Y Position (pixels)')
ax1.invert_yaxis()
ax1.legend()
ax1.grid(True, alpha=0.3)

# Plot 2: Position over time
frames = np.arange(len(trajectory))
ax2.plot(frames, trajectory[:, 0], 'b-', label='X Position', alpha=0.7)
ax2.plot(frames, trajectory[:, 1], 'r-', label='Y Position', alpha=0.7)
ax2.set_title('Position Over Time')
ax2.set_xlabel('Frame Number')
ax2.set_ylabel('Position (pixels)')
ax2.legend()
ax2.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('trajectory_plot.png', dpi=150)
plt.show()